### ISSUE TITLE
Remove red line in custom view

### ISSUE THREAD

**Issue by gary-phantom** [phantomcyber/reversinglabs-tiscale#14]
![screen shot 2018-02-07 at 5 31 19 pm](https://user-images.githubusercontent.com/32378564/35950756-dfa13d56-0c2c-11e8-9f80-9c41707674b5.png)

The attached file shows the redline just below the "ReversingLabs" text which should be removed

**Comment by pzhou-splunk** [comment]
Hello!

This repo has been migrated to our new GitHub org. Please find a copy of this issue at https://github.com/splunk-soar-connectors/reversinglabs-tiscale/issues/1
