### ISSUE TITLE
Lots of actions in connector are not present in JSON

### ISSUE THREAD

**Issue by phantom-developer** [phantomcyber/reversinglabs-tiscale#5]
There are 4 actions in the connector file which are not in the JSON. Looking at them, it seems like they should work -- is there a reason these are not included?

**Comment by pzhou-splunk** [comment]
Hello!

This repo has been migrated to our new GitHub org. Please find a copy of this issue at https://github.com/splunk-soar-connectors/reversinglabs-tiscale/issues/2
